# dockerのイメージは本ファイルから生成

FROM php:7.4-fpm

# イメージのビルド時に実行するコマンド
RUN apt-get update && \
  apt-get install -y libgmp-dev git libonig-dev && \
  docker-php-ext-install pdo_mysql mysqli mbstring gmp

# composerのイメージからdockerコマンドだけコピー
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer
